### ISSUE TITLE
Missing start and stop time on Toggl Desktop

### ISSUE THREAD

**Issue by jarlarntzen** [toggl/toggldesktop#1899]
On Toggl mobile there is a very handy display of the start and end times of the current work session.
This has helped me quite a bit when I have left work and forgotten to stop the Toggl timer. In Toggl Mobile I can then simply reset the end time back to the time when I left work and get a correct number of registered hours without having to remember the start time.
![toggl-mobile 2016-05-06](https://cloud.githubusercontent.com/assets/2108412/15081631/0d9d2a02-13c4-11e6-8176-780b1f0d05d2.jpg)
I would love to simply have the same feature in Toggle Desktop as I expect I'm not the only one to forget stopping the timer before leaving work. Also, it does work as a verification that the timer was indeed started at the right time as well.
![toggl-desktop 2016-05-06](https://cloud.githubusercontent.com/assets/2108412/15081398/1efc20a6-13c3-11e6-8960-c23e9efd1d86.jpg)

Thanks!

**Comment by IndrekV** [comment]
Hi,

Toggl Desktop also shows start and stop times in the edit popup. In your screenshot you are viewing a time entry created in "duration only" mode in which case start and stop times are not saved and not shown. If you disable the duration only mode the app would show start and end fields. The duration only mode can be changed in the web app profile view: https://toggl.com/app/profile

![duration_only](https://cloud.githubusercontent.com/assets/842229/15090809/7cc2b946-143d-11e6-94e7-e26173fd5ab1.png)

Here is how it looks like with non duration only mode.
![edit_popup](https://cloud.githubusercontent.com/assets/842229/15090813/8c396514-143d-11e6-9e50-68441237bfe3.png)

Note also that entries created with "duration only" mode will never show the start stop time event when changing the setting as the setting is saved with the time entry.

**Comment by jarlarntzen** [comment]
@indrekV: Ok. Thank you. I'll try that but still there is a mismatch with how the mobile application currently works. Even in "Duration mode", the mobile application offers to modify start/end times. If there are multiple time entries, the mobile app will show the total and then list all durations on expanding the total.
![toggl-mobile 2016-05-10](https://cloud.githubusercontent.com/assets/2108412/15142263/9d6c7178-16a4-11e6-9ec7-0adf88f149a6.jpg)
----
Even after changing the time tracking setting to "Save start and stop times" a couple of days ago there is no change in the client, neither on OSX or on Ubuntu 14.04 LTS.  Maybe it's due to some fuss with the workspace? (I have projects in 2 different ones)

**Comment by IndrekV** [comment]
Might be because workspace settings have not synced properly. Loging out and back in should fix that. Also as I stated before: `Entries created with "duration only" mode will never show the start stop time even when changing the setting as the setting is saved with the time entry.`

This means if you change the setting the entries created while in duration only mode will still no show start stop times. Also if you continue such entry it will act as duration only and will not create new entry.

**Comment by ferantivero** [comment]
I've created a new account, bc I had to and it came out along with the New Design. I think but not 100% sure, since I've switched to the new account in the mac desktop app it is kind of configured in "duration-time only". So now, from the New Design profile , it is not displayed the options "when tracking time".

What am I missing guys?

**Comment by IndrekV** [comment]
The issue you are describing with duration only mode is fixed in latest beta (version 7.3.349 ). Please switch to beta channel from the about view and update the app.

**Comment by ferantivero** [comment]
it just worked like a charm :shipit: 👍 . The only thing is that I couldn't get what you mean by 

> switch to beta channel from the "about view" and update the app. 

I've tried from the current mac os stable desktop app (about option) and from the web app without luck. Is that feature actually released?

I've downloaded the beta specific version from https://github.com/toggl/toggldesktop/releases/download/v7.3.349/TogglDesktop-7_3_349.dmg 

Thanks,

**Comment by IndrekV** [comment]
The channel switching is available in the version from our website. The AppStore version does not have the channel select in About window. See screenshot of the About view with "Release channel" select box.

![about_view_macos](https://cloud.githubusercontent.com/assets/842229/20178532/4d21ab9c-a75a-11e6-80c6-d4cce5941bb5.png)

**Comment by ferantivero** [comment]
yeah, once I installed the beta version from the About view it is being displayed. It made my day 😃 

thanks for your support!

**Comment by skozin** [comment]
I've changed release channel to `beta`, and now I see start-end fields for new entries. But I still cannot see them for the ones created before the update. Is this expected?

**Comment by IndrekV** [comment]
@skozin This is expected. At the time entry creation moment it is defined if the entry keeps start stop time or not. It can not be changed after entry creation.

**Comment by skozin** [comment]
@IndrekV, and what about entries created in mobile version of the app? Apparently, they store start and end times, as I can change them from the mobile app. But not from the desktop one. Is this expected?

**Comment by IndrekV** [comment]
It seems that there is a bug when displaying start stop times for certain entries I'll fix it and will release it to beta channel.

**Comment by skozin** [comment]
@IndrekV, thanks a lot! :)

**Comment by JamesR404v2** [comment]
I seem to have the same issue as the OP, but now it's 2018.

Could it be that this issue is still not fixed? Or is my issue having a different cause, in which case I suppose it's more appropriate to create a new thread.

**Comment by IndrekV** [comment]
@JamesR404v2 Please send feedback from the app and mention it's for Indrek. That way I get more info and can see if I can replicate it.

**Comment by JamesR404v2** [comment]
Great, thanks! I just submitted the feedback via the app, to your
attention  @Indrek

**Comment by IndrekV** [comment]
The issue was caused by old Android app that still created duration only entries when continuing and old duration only entry.

**Comment by JamesR404v2** [comment]
Okay, right now I seem to have the latest version installed.

I don't have automatic updating, I updated some apps yesterday, but I don't
know if Toggl was among them.

But basically you're saying the issue shouldn't occur anymore? I'll keep an
eye on this next week.

**Comment by JamesR404v2** [comment]
Ah, I see! That is totally new, I've installed the app and will see that
the problem is fixed.

Thanks!!
